name: '.ps1 to .exe'

on:
  push:
    branches-ignore:
      - main
      
    paths:
      - 'input/*.ps1'
      - 'input/*.ico'
    
  workflow_dispatch: {}

jobs:
  build:
    if: github.ref_type == 'branch'
    runs-on: windows-2025

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install ps2exe'
        run: Install-Module -Name ps2exe -Force -Scope CurrentUser -AllowClobber
        shell: pwsh

      - name: 'Build .exe from all .ps1 in /input'
        run: |
          $folder = ".\input"
          
          if (-Not (Test-Path $folder)) {
            Write-Host "Ordner '$folder' existiert nicht. Abbruch."
            exit 1
          }
          
          $ps1Files = Get-ChildItem -Path $folder -Filter *.ps1
          if ($ps1Files.Count -eq 0) {
            Write-Host "Keine .ps1-Dateien im Ordner '$folder' gefunden. Abbruch."
            exit 1
          }
          
          New-Item -ItemType Directory -Path output -Force | Out-Null
          
          foreach ($file in $ps1Files) {
            $exeName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name) + ".exe"
            $exePath = Join-Path -Path "output" -ChildPath $exeName
            
            
            $iconPath = Join-Path -Path $folder -ChildPath ([System.IO.Path]::GetFileNameWithoutExtension($file.Name) + ".ico")
            
            if (-Not (Test-Path $iconPath)) {
              Write-Host "Keine Icon-Datei für $($file.Name) gefunden, baue ohne Icon."
              $iconPath = $null
            } else {
              Write-Host "Verwende Icon $iconPath für $($file.Name)"
            }
            
            Write-Host "Baue $exePath aus $($file.Name)"
            if ($iconPath) {
              Invoke-ps2exe $file.FullName $exePath -iconFile $iconPath
            } else {
              Invoke-ps2exe $file.FullName $exePath
            }
          }
        shell: pwsh

      - name: 'Upload all .exe artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/*.exe
      
      - name: 'Commit and push generated files'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add output/
          git commit -m "Upload generated files"
          
          $branch = "${{ github.ref_name }}"
          git push origin HEAD:$branch
        shell: pwsh
